### ISSUE TITLE
FACE_DETECTION gives not correct response

### ISSUE THREAD

**Issue by rusakovic** [googleapis/nodejs-video-intelligence#627] opened 2021-11-01 15:25 UTC
Hello.
I use Firestore Emulator on local.

installed ` "@google-cloud/video-intelligence": "^3.4.1",`

My function:
```js
import * as functions from "firebase-functions";
import { readFileSync } from "fs";
import { VideoIntelligenceServiceClient } from "@google-cloud/video-intelligence";
import { google } from "@google-cloud/video-intelligence/build/protos/protos";

export const videoFaceRecognition = functions.https.onCall(async () => {
   const client = new VideoIntelligenceServiceClient({
      keyFile:
         "/Volumes/video_cred.json",
   });

   const gcsUri = "/Volumes/Main/max_park_10_sec.mp4";

   const file = readFileSync(gcsUri);

   const inputContent = file.toString("base64");

   const request: google.cloud.videointelligence.v1.IAnnotateVideoRequest = {
      inputContent: inputContent,
      features: [google.cloud.videointelligence.v1.Feature.FACE_DETECTION],
      videoContext: {
         faceDetectionConfig: {
            // Must set includeBoundingBoxes to true to get facial attributes.
            includeBoundingBoxes: true,
            includeAttributes: true,
         },
      },
   };

   const [operation] = await client.annotateVideo(request);
   const results = await operation.promise();
   console.log("Waiting for operation to complete...");
   console.log(
      "🚀 ~ file: videoFaceRecognition.ts ~ line 28 ~ detectFace ~ results",
      JSON.stringify(results)
   );
});

```

And got such result
```json
[
  {
    "annotationResults": [
      {
        "segment": {
          "startTimeOffset": {},
          "endTimeOffset": {
            "nanos": 233566000
          }
        }
      }
    ]
  },
  {
    "annotationProgress": [
      {
        "progressPercent": 100,
        "startTime": {
          "seconds": "1635779202",
          "nanos": 720191000
        },
        "updateTime": {
          "seconds": "1635779207",
          "nanos": 908290000
        }
      }
    ]
  },
  {
    "name": "projects/843010621370/locations/europe-west1/operations/1210927764137298132",
    "metadata": {
      "type_url": "type.googleapis.com/google.cloud.videointelligence.v1.AnnotateVideoProgress",
      "value": {
        "type": "Buffer",
        "data": [
          10,
          30,
          16,
          100,
          26,
          12,
          8,
          130,
          133,
          128,
          140,
          6,
          16,
          152,
          252,
          180,
          215,
          2,
          34,
          12,
          8,
          135,
          133,
          128,
          140,
          6,
          16,
          208,
          207,
          141,
          177,
          3
        ]
      }
    },
    "done": true,
    "response": {
      "type_url": "type.googleapis.com/google.cloud.videointelligence.v1.AnnotateVideoResponse",
      "value": {
        "type": "Buffer",
        "data": [
          10,
          11,
          82,
          9,
          10,
          0,
          18,
          5,
          16,
          176,
          222,
          175,
          111
        ]
      }
    },
    "result": "response"
  }
]
```

But according to docs: https://cloud.google.com/video-intelligence/docs/face-detection#face_detection_from_a_file_in
I should receive it: `results[0].annotationResults[0].faceDetectionAnnotations`

But `faceDetectionAnnotations` are not existed in response.

How to debug it?

I use this video:

https://user-images.githubusercontent.com/17801144/139696291-cc2be60f-0647-4f94-9e71-edb18beb3c0d.mp4

Thank you for your help!

**Comment by galz10** [comment] 2021-12-09 19:15
Hi @rusakovic i looked at your code and the video, the only difference i see in your code and the documentation sample code is that you use `google.cloud.videointelligence.v1.Feature.FACE_DETECTION` instead of `FACE_DETECTION` but this shouldn't be a problem as long as the  `google.cloud.videointelligence.v1.Feature.FACE_DETECTION` is populated .

I tested your code with a longer video (2 seconds) and it returned the faceDetectionAnnotations. I suggest recording a longer video probably longer than 1 second (your video 0.233566 seconds). 

I'll close this issue because it seems like the issue is with the length of the video, if my suggestions didn't fix this issue feel free to reopen the issue.

**Closed by galz10** 2021-12-09 19:15 UTC
Labels: type: question, api: videointelligence
